services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local

  front:
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules

  database:
    ports:
      - "5432:5432"
