services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      args:
        user: myuser
        uid: 1000
    container_name: laravel_app
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=ecommerce
      - DB_USERNAME=postgres
      - DB_PASSWORD=just
    volumes:
      - ./back:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - app_network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: react_app
    depends_on : 
      - back  
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: pgsql_db
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  vendor:
