version: '3.8'

services:
  back:
    build:
      context: ./back
      args:
        user: myuser  # Specify the user name here
        uid: 1000     # Specify the user ID here (it can be any valid UID)
    container_name: laravel_app
    restart: always
    depends_on:
      - database
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=database  # Ensure this is pointing to the correct database service
      - DB_PORT=5432
      - DB_DATABASE=ecommerce
      - DB_USERNAME=postgres
      - DB_PASSWORD=just
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html
      - vendor:/var/www/html/vendor  # Persist the vendor directory
    networks:
      - app_network

  front:
    build: ./front
    container_name: react_app
    restart: always
    depends_on:
      - back
    ports:
      - "3000:3000"
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: pgsql_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: just
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  vendor:  # Persist the Laravel vendor directory for caching dependencies
