version: '3.8'

services:
  back:
    build:
      context: ./back
      args:
        user: myuser
        uid: 1000
    container_name: laravel_app
    depends_on:
      - database
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=ecommerce
      - DB_USERNAME=postgres
      - DB_PASSWORD=just
    volumes:
      - ./back:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - app_network

  front:
    build: ./front
    container_name: react_app
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: pgsql_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: just
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  vendor:
