version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl_certs:/etc/nginx/ssl:ro
      - front_build:/usr/share/nginx/html
      - back_storage:/var/www/html/storage/app/public
    depends_on:
      - back
    restart: always
    networks:
      - app-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    volumes:
      - back_storage:/var/www/html/storage/app/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  front_build:
  back_storage:
  ssl_certs:
